FROM python:3.9-slim-bullseye

RUN pip install mlflow

RUN mkdir /mlruns

EXPOSE 5000

CMD mlflow server \
    --backend-store-uri /mlruns \
    --default-artifact-root /mlruns \
    --host 0.0.0.0 \
    --port 5000
